# Generated by Django 4.1.7 on 2023-03-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='order',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='ordering.ingredient'),
        ),
    ]
